name: dennylungu-com
services:
    web:
        build: ./web/
        stdin_open: true
        tty: true
        container_name: web
        expose:
            - 80
        environment:
            - "VIRTUAL_HOST=dennylungu.com"
            - "VIRTUAL_PORT=80"

    web2:
        build: ./web2/
        stdin_open: true
        tty: true
        container_name: web2
        expose:
            - 80
        environment:
            - "VIRTUAL_HOST=1.dennylungu.com"
            - "VIRTUAL_PORT=80"

    web3:
        build: ./web3/
        stdin_open: true
        tty: true
        container_name: web3
        expose:
            - 80
        environment:
            - "VIRTUAL_HOST=2.dennylungu.com"
            - "VIRTUAL_PORT=80"

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: reverse-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock